apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  jvm.options: |-
    ## GC configuration
    -XX:G1ConcRefinementThreads=8
    -XX:GCDrainStackTargetSize=64
    -XX:+SegmentedCodeCache
    -XX:+UseCompressedClassPointers
    -XX:+UseCompressedOops
    -XX:+UseG1GC
    -XX:+AlwaysPreTouch
    -server
    -Xss1m
    -Djava.awt.headless=true
    -Dfile.encoding=UTF-8
    -Djna.nosys=true
    -XX:-OmitStackTraceInFastThrow
    -Dio.netty.noUnsafe=true
    -Dio.netty.noKeySetOptimization=true
    -Dio.netty.recycler.maxCapacityPerThread=0
    -Dlog4j.shutdownHookEnabled=false
    -Dlog4j2.disable.jmx=true

  log4j2.properties: |-
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console

  elasticsearch.yml: |-
    cluster:
      name: {{ .Values.common.env.CLUSTER_NAME }}

    node:
      master: ${NODE_MASTER:true}
      data: ${NODE_DATA:true}
      name: ${NODE_NAME}
      ingest: ${NODE_INGEST:true}
      max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES:1}

    network.host: ${NETWORK_HOST:_local_}

    path:
      data: /storage/data
      logs: /storage/logs

    bootstrap:
      memory_lock: ${MEMORY_LOCK:false}

    http:
      enabled: ${HTTP_ENABLE:true}
      compression: true
      cors:
        enabled: ${HTTP_CORS_ENABLE:false}
        allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:"*"}

    indices:
      memory.index_buffer_size: 30%

    #index:
    #  refresh_interval: 30s

    discovery:
      zen:
        ping.unicast.hosts: ${DISCOVERY_SERVICE:}
        minimum_master_nodes: ${NUMBER_OF_MASTERS:1}

    # see https://github.com/elastic/elasticsearch-definitive-guide/pull/679
    processors: ${PROCESSORS:}
    {{- if .Values.tls.enable }}
    opendistro_security:
      {{- if .Values.opendistro_security.enable }}
      advanced_modules_enabled: {{ .Values.opendistro_security.advanced_modules_enabled }}
      restapi:
        roles_enabled: ["all_access"]
      nodes_dn:
        - "CN=*.{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.tls.clusterDomain }}"
      authcz:
        admin_dn:
          - "CN=admin.{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.tls.clusterDomain }},OU=securityadmin,O=logging"
      {{- end }}
      ssl:
        http:
          clientauth_mode: REQUIRE
          enabled: true
          enabled_protocols:
          - "TLSv1.3"
          - "TLSv1.2"
          pemkey_filepath: tls/tls.key
          pemcert_filepath: tls/tls.crt
          pemtrustedcas_filepath: tls/ca.crt
        transport:
          pemkey_filepath: tls/tls.key
          pemcert_filepath: tls/tls.crt
          pemtrustedcas_filepath: tls/ca.crt
    {{- end }}

{{- if .Values.common.config }}
{{ toYaml .Values.common.config | indent 4 }}
{{- end }}
