{{- if .Values.opendistro_security.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-security-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  action_groups.yml: |-
    UNLIMITED:
      readonly: true
      permissions:
        - "*"
    INDICES_ALL:
      readonly: true
      permissions:
        - "indices:*"
    MANAGE:
      readonly: true
      permissions:
        - "indices:monitor/*"
        - "indices:admin/*"
    CREATE_INDEX:
      readonly: true
      permissions:
        - "indices:admin/create"
        - "indices:admin/mapping/put"
    MANAGE_ALIASES:
      readonly: true
      permissions:
        - "indices:admin/aliases*"
    INDICES_MONITOR:
      readonly: true
      permissions:
        - "indices:monitor/*"
    DATA_ACCESS:
      readonly: true
      permissions:
        - "indices:data/*"
        - CRUD
    WRITE:
      readonly: true
      permissions:
        - "indices:data/write*"
        - "indices:admin/mapping/put"
    READ:
      readonly: true
      permissions:
        - "indices:data/read*"
        - "indices:admin/mappings/fields/get*"
    DELETE:
      readonly: true
      permissions:
        - "indices:data/write/delete*"
    CRUD:
      readonly: true
      permissions:
        - READ
        - WRITE
    SEARCH:
      readonly: true
      permissions:
        - "indices:data/read/search*"
        - "indices:data/read/msearch*"
        - SUGGEST
    SUGGEST:
      readonly: true
      permissions:
        - "indices:data/read/suggest*"
    INDEX:
      readonly: true
      permissions:
        - "indices:data/write/index*"
        - "indices:data/write/update*"
        - "indices:admin/mapping/put"
        - "indices:data/write/bulk*"
    GET:
      readonly: true
      permissions:
        - "indices:data/read/get*"
        - "indices:data/read/mget*"

    CLUSTER_ALL:
      readonly: true
      permissions:
        - "cluster:*"
    CLUSTER_MONITOR:
      readonly: true
      permissions:
        - "cluster:monitor/*"
    CLUSTER_COMPOSITE_OPS_RO:
      readonly: true
      permissions:
        - "indices:data/read/mget"
        - "indices:data/read/msearch"
        - "indices:data/read/mtv"
        - "indices:data/read/coordinate-msearch*"
        - "indices:admin/aliases/exists*"
        - "indices:admin/aliases/get*"
        - "indices:data/read/scroll"
    CLUSTER_COMPOSITE_OPS:
      readonly: true
      permissions:
        - "indices:data/write/bulk"
        - "indices:admin/aliases*"
        - CLUSTER_COMPOSITE_OPS_RO
    MANAGE_SNAPSHOTS:
      readonly: true
      permissions:
        - "cluster:admin/snapshot/*"
        - "cluster:admin/repository/*"
  config.yml: |-
    opendistro_security:
      dynamic:
        kibana:
          multitenancy_enabled: false
          server_username: {{ .Values.opendistro_security.kibana_user }}
          index: '.kibana'
          do_not_fail_on_forbidden: false
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: true
            internalProxies: '.+' # since we require clientauth cert for http, we do not need to do IP filtering
            remoteIpHeader:  'x-forwarded-for'
            proxiesHeader:   'x-forwarded-by'
            trustedProxies: '.+' # trust all external proxies, regex pattern
        authc:
          proxy_auth_domain:
            http_enabled: true
            transport_enabled: false
            order: 0
            http_authenticator:
              type: proxy
              challenge: false
              config:
                user_header: "x-forwarded-email"
                #roles_header: "x-proxy-roles"
            authentication_backend:
              type: noop
          clientcert_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: clientcert
              config:
                username_attribute: ou #optional, if omitted DN becomes username
              challenge: false
            authentication_backend:
              type: noop
  roles.yml: |-
    # Allows everything, but no changes to opendistro_security configuration index
    all_access:
      readonly: true
      cluster:
        - UNLIMITED
      indices:
        '*':
          '*':
            - UNLIMITED
      tenants:
        admin_tenant: RW

    # Read all, but no write permissions
    readall:
      readonly: true
      cluster:
        - CLUSTER_COMPOSITE_OPS_RO
      indices:
        '*':
          '*':
            - READ

    # Read all and monitor, but no write permissions
    readall_and_monitor:
      cluster:
        - CLUSTER_MONITOR
        - CLUSTER_COMPOSITE_OPS_RO
      indices:
        '*':
          '*':
            - READ

    # For users which use kibana, access to indices must be granted separately
    kibana_user:
      readonly: true
      cluster:
        - MONITOR
        - CLUSTER_COMPOSITE_OPS_RO
      indices:
        '?kibana':
          '*':
            - MANAGE
            - INDEX
            - READ
            - DELETE
        '?tasks':
          '*':
            - INDICES_ALL
        '?management-beats':
          '*':
            - INDICES_ALL
        '*':
          '*':
            - "indices:data/read/field_caps"
            - indices:data/read/xpack/rollup*
            - indices:admin/mappings/get*
            - indices:admin/get

    # For the kibana server
    kibana_server:
      readonly: true
      cluster:
        - CLUSTER_MONITOR
        - CLUSTER_COMPOSITE_OPS
        - CLUSTER_COMPOSITE_OPS
        - cluster:admin/xpack/monitoring*
        - indices:admin/template*
        - indices:data/read/scroll*
        - indices:data/write/reindex
      indices:
        'logstash-*':
          '*':
            - "indices:data/read/field_caps*"
        'tracing-*':
          '*':
            - "indices:data/read/field_caps*"
        'k8slogs-*':
          '*':
            - "indices:data/read/field_caps*"
        '?kibana':
          '*':
            - INDICES_ALL
        '?kibana-6':
          '*':
            - INDICES_ALL
        '?kibana_*':
          '*':
            - INDICES_ALL
        '?reporting*':
          '*':
            - INDICES_ALL
        '?monitoring*':
          '*':
            - INDICES_ALL
        '?tasks':
          '*':
            - INDICES_ALL
        '?management-beats*':
          '*':
            - INDICES_ALL
        '*':
          '*':
            - "indices:admin/aliases*"

    spanwrite:
      readonly: true
      cluster:
        - CLUSTER_MONITOR
        - CLUSTER_COMPOSITE_OPS
        - "indices:admin/template/get"
        - "indices:admin/template/put"
      indices:
        'jaeger-*':
          '*':
            - WRITE
            - CREATE_INDEX

    spanread:
      cluster:
        - CLUSTER_MONITOR
      readonly: true
      indices:
        'jaeger-*':
          '*':
            - READ

    logreader:
      readonly: true
      indices:
        'jaeger-*':
          '*':
            - READ
        'logstash-*':
          '*':
            - READ
        'k8slogs-*':
          '*':
            - READ

    # For logstash and beats
    logwrite:
      readonly: true
      cluster:
        - CLUSTER_MONITOR
        - CLUSTER_COMPOSITE_OPS
        - "indices:admin/template/get"
        - "indices:admin/template/put"
      indices:
        'logstash-*':
          '*':
            - WRITE
            - CREATE_INDEX
        'k8slogs-*':
          '*':
            - WRITE
            - CREATE_INDEX
        '*beat*':
          '*':
            - WRITE
            - CREATE_INDEX

    prometheus:
      readonly: true
      cluster:
        - CLUSTER_MONITOR
      indices:
        '*':
          '*':
            - INDICES_MONITOR

    curator:
      readonly: true
      cluster:
        - CLUSTER_MONITOR
        - CLUSTER_COMPOSITE_OPS
      indices:
        '*':
          '*':
            - READ
            - INDICES_MONITOR
        'tracing-*':
          '*':
            - READ
            - INDICES_MONITOR
            - DELETE
        'k8slogs-*':
          '*':
            - READ
            - INDICES_MONITOR
            - DELETE
        'logstash-*':
          '*':
            - READ
            - INDICES_MONITOR
            - DELETE

    # Allows adding and modifying repositories and creating and restoring snapshots
    manage_snapshots:
      readonly: true
      cluster:
        - MANAGE_SNAPSHOTS
      indices:
        '*':
          '*':
            - "indices:data/write/index"
            - "indices:admin/create"

    # View and acknowledge alerts for Open Distro for Elasticsearch Alerting
    alerting_acknowledge:
      readonly： true
      indices:
        '.opendistro-alerting-alerts':
          '*':
            - CRUD

    # Create, update, and delete monitors and destinations for Open Distro for Elasticsearch Alerting
    alerting_monitors:
      readonly： true
      indices:
        '.opendistro-alerting-config':
          '*':
            - CRUD

    # Read only for Open Distro for Elasticsearch Alerting
    alerting_read_only:
      readonly： true
      indices:
        '.opendistro-alerting-config':
          '*':
            - READ
        '.opendistro-alerting-alerts':
          '*':
            - READ

    # Allows each user to access own named index
    own_index:
      cluster:
        - CLUSTER_COMPOSITE_OPS
      indices:
        '${user_name}':
          '*':
            - INDICES_ALL

  roles_mapping.yml: |-
    curator:
      readonly: true
      users:
        - curator
    prometheus:
      readonly: true
      users:
        - prometheus
    spanread:
      readonly: true
      users:
        - span-read
    spanwrite:
      readonly: true
      users:
        - span-write
    all_access:
      readonly: true
      users:
        - curator
{{ toYaml .Values.opendistro_security.admins | indent 8 }}
      backendroles:
        - admin
    logwrite:
      users:
        - logwrite
    kibana_server:
      readonly: true
      users:
        - kibana
    kibana_user:
      users:
{{ toYaml .Values.opendistro_security.users | indent 8 }}
    alerting_acknowledge:
      users:
{{ toYaml .Values.opendistro_security.users | indent 8 }}
    alerting_monitors:
      users:
{{ toYaml .Values.opendistro_security.users | indent 8 }}
    logreader:
      users:
{{ toYaml .Values.opendistro_security.users | indent 8 }}
      backendroles:
        - kibanauser
    readall:
      readonly: true
      backendroles:
        - readall
    manage_snapshots:
      readonly: true
      backendroles:
        - snapshotrestore
    own_index:
    own_index:
      users:
        - '*'

  internal_users.yml: |-
    # This is the internal user database
    # The hash value is a bcrypt hash and can be generated with plugin/tools/hash.sh
    {}
{{- end -}}
