{{ if .Values.opendistro_security.enable }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: securityinit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-securityadmin-credentials
  namespace: {{ .Release.Namespace }}
type: tls
data:
{{- end }}
