{{- if .Values.opendistro_security.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-securityinit
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  activeDeadlineSeconds: {{ default 600 .Values.opendistro_security.init.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      serviceAccountName: "{{ template "fullname" . }}-securityinit"
      subdomain: "{{ template "fullname" . }}"
      initContainers:
        - name: generate-tls-pair
          image: "{{ .Values.tls.image }}:{{ .Values.tls.imageTag }}"
          imagePullPolicy: {{ .Values.tls.imagePullPolicy }}
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SUBDOMAIN
            value: {{ template "fullname" . }}
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          args:
          - "-namespace=$(NAMESPACE)"
          - "-pod-ip=$(POD_IP)"
          - "-pod-name=$(POD_NAME)"
          - "-hostname=admin"
          - "-subdomain=$(SUBDOMAIN)"
          - "-organizational-units=securityadmin"
          - "-organizations=logging"
          - "-headless-name-as-cn"
          - "-pkcs8"
          - "-labels=component={{ template "fullname" . }}"
          - "-secret-name={{ template "fullname" . }}-securityadmin-credentials"
        - name: wait-for-es
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "until nc -w 1 -z {{ template "fullname" . }} 9300; do echo waiting for elasticsearch to come up; sleep 2; done"
      containers:
      - name: securityinit
        image: "{{ .Values.opendistro_security.init.image }}:{{ .Values.opendistro_security.init.imageTag }}"
        imagePullPolicy: "Always"
        args:
          - "--configdir"
          - "/securityconfig/"
          - "-cacert"
          - "/tls/ca.crt"
          - "--clustername"
          - "{{ .Values.common.env.CLUSTER_NAME }}"
          - "--hostname"
          - "{{ template "fullname" . }}-discovery.{{ .Release.Namespace }}.svc.{{ .Values.tls.clusterDomain }}"
          - "-cert"
          - "/tls/tls.crt"
          - "-key"
          - "/tls/tls.key"
        volumeMounts:
          - name: tls
            mountPath: /tls
          - name: security-config
            mountPath: /securityconfig
      volumes:
        - name: tls
          secret:
            secretName: {{ template "fullname" . }}-securityadmin-credentials
            defaultMode: 0400
        - name: security-config
          configMap:
            name: {{ template "fullname" . }}-security-config
      restartPolicy: {{ .Values.opendistro_security.init.restartPolicy }}
{{- end }}
