{{- if .Values.opendistro_security.enable }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: securityinit
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-securityinit
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - "{{ template "fullname" . }}-securityadmin-credentials"
    verbs:
      - update
      - get
{{- end -}}
{{- end -}}

